img_size: 640
batch: 128
epochs: 500
patience: 50
save_period: 50
device: 0
data: datasets/cyclist_yolo/data.yaml
model: runs/warmup/cyclist_only/weights/best.pt  # ← Use warm-up checkpoint
project: runs/finetune
