# Model
# model: models/20250629_warmup_best.pt
# model: models/yolo11n.pt
ver: 0.1 beta
# ncnn_model_path: models/yolo11n_ncnn_model/
ncnn_model_path: models/20250629_warmup_best_ncnn_model/

# Camera settings
camera_source: tests/test.mov # or use 0 for real-time camera
frame_width: 640
frame_height: 480
frame_skip: 5

# Inference settings
imgsz: 640
confidence_threshold: 0.65
draw_bbox: true

# Logging and metadata
location: UCD
camera_id: cam01
logging_enabled: true
log_interval_minutes: 5

# Display settings
refresh_interval_seconds: 10

# sort.py
sort_max_age: 90
sort_iou_threshold: 0.3


# main.py
# Check for low light conditions every X minutes
LOW_LIGHT_CHECK_INTERVAL: 15
# Threshold for low light detection (average pixel value)
LOW_LIGHT_THRESHOLD: 50
# Hours to run camera alignment check (e.g., 6 AM and 6 PM)
CAMERA_ALIGNMENT_HOURS: [6, 18]
# Motion detection sensitivity (area of the largest contour)
MOTION_SENSITIVITY: 500
# Reference frame for camera alignment check
REFERENCE_FRAME_PATH: "data/img/reference_frame.jpg"
# Threshold for camera alignment check (structural similarity index)
ALIGNMENT_THRESHOLD: 0.9
# Email settings for notifications
EMAIL_SENDER: "your_email@gmail.com"
EMAIL_PASSWORD: "your_password"
EMAIL_RECIPIENT: "recipient_email@example.com"
EMAIL_SUBJECT: "Camera Alignment Alert"
EMAIL_BODY: "Camera may be misaligned. Please check."
