import "server-only";
import { promises as fs } from "node:fs";
import path from "node:path";
import { mockCity } from "./data-source";

// Reads the JSON fixtures generated by scripts/generate_mock_dublin.py.
// Files live in ../data/mock/{city}/ relative to this repo's root.

const ROOT = path.resolve(process.cwd(), "..", "data", "mock", mockCity);

export interface MockStreet {
  id: string;
  display_name: string;
  osm_way_ids: number[];
  geom: GeoJSON.MultiLineString;
  bbox: GeoJSON.Polygon;
  city: string;
  active: boolean;
}

export interface MockSensor {
  id: string;
  display_name: string;
  latitude: number;    // admin-only — never leaks to public responses
  longitude: number;   // admin-only
  install_date: string;
  active: boolean;
  config_json: Record<string, unknown>;
  config_version: string;
  last_heartbeat: string | null;
  fw_version: string;
  notes: string;
}

export interface MockCoverage {
  sensor_id: string;
  street_id: string;
  weight: number;
}

export interface MockReading {
  sensor_id: string;
  window_start: string;
  window_end: string;
  class_name: string;
  count: number;
  avg_speed_kmh: number | null;
  partial: boolean;
}

export interface MockDailyTotal {
  sensor_id: string;
  day: string;
  totals_json: Record<string, number>;
  window_count: number;
  late: boolean;
  reconciled: boolean;
}

export interface MockHeartbeat {
  sensor_id: string;
  ts: string;
  uptime_s: number;
  cpu_temp_c: number;
  last_window_end: string;
  config_version: string;
}

async function readJson<T>(file: string): Promise<T> {
  const raw = await fs.readFile(path.join(ROOT, file), "utf-8");
  return JSON.parse(raw) as T;
}

let cache: {
  streets?: MockStreet[];
  sensors?: MockSensor[];
  coverage?: MockCoverage[];
  readings?: MockReading[];
  daily?: MockDailyTotal[];
  heartbeats?: MockHeartbeat[];
} = {};

export async function loadStreets(): Promise<MockStreet[]> {
  cache.streets ??= await readJson<MockStreet[]>("streets.json");
  return cache.streets;
}

export async function loadSensors(): Promise<MockSensor[]> {
  cache.sensors ??= await readJson<MockSensor[]>("sensors.json");
  return cache.sensors;
}

export async function loadCoverage(): Promise<MockCoverage[]> {
  cache.coverage ??= await readJson<MockCoverage[]>("sensor_street_coverage.json");
  return cache.coverage;
}

export async function loadReadings(): Promise<MockReading[]> {
  cache.readings ??= await readJson<MockReading[]>("sensor_readings.json");
  return cache.readings;
}

export async function loadDaily(): Promise<MockDailyTotal[]> {
  cache.daily ??= await readJson<MockDailyTotal[]>("sensor_daily_totals.json");
  return cache.daily;
}

export async function loadHeartbeats(): Promise<MockHeartbeat[]> {
  cache.heartbeats ??= await readJson<MockHeartbeat[]>("sensor_heartbeats.json");
  return cache.heartbeats;
}
