# config.yaml

# Model and tracker
model: models/yolo11n.pt
tracker: bytetrack.yaml

# Camera settings
camera_source: test_video/test.mov # or use 0 for real-time camera
frame_width: 640
frame_height: 480
frame_skip: 2

# Inference settings
imgsz: 640
confidence_threshold: 0.5
draw_bbox: true

# Logging and metadata
location: UCD
camera_id: cam01
logging_enabled: true
log_interval_minutes: 5
